name: ds

on:
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      reason:
        description: '触发原因'
        required: true
        default: '手动生成ds.txt文件'

jobs:
  generate-ds:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        # 如果有依赖需要安装，可以在这里添加
        # pip install -r requirements.txt
        
    - name: 运行生成脚本
      run: python ds.py
      
    - name: 提交生成的文件
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ds.txt
        git commit -m "自动生成ds.txt文件" -a || echo "没有更改可提交"
        git push
